<a href="https://colab.research.google.com/github/Satyasai000111/Saiteja-FMML-LABS/blob/main/NUMPYprasad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY is a numerical python is a library coinsisting of a multidimensional array objects
USES: 1) linear algebra
2)Matrix operations
3)Mathematicla operations etc

In [1]:
#
import numpy as np
a=np.array([1,2,3,4])
a


array([1, 2, 3, 4])

In [2]:
import numpy as np
a=np.array([1,3,5])
b=np.array([1,2,3])
print(a*b)

[ 1  6 15]


In [3]:
b=np.array([[1,2,3,4],[5,6,7,8]])
b
#([[],[]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
a=np.array([1,3,5])
b=np.array([[1,2,3],[6.7,8,9]])
a.ndim,b.ndim

(1, 2)

In [5]:
b=np.array([[1,2,3],[6.7,8,9]])
b.shape
b

array([[1. , 2. , 3. ],
       [6.7, 8. , 9. ]])

In [6]:
import numpy as np
var = np.array([[1,2,3,9,0],[4,5,6,6,9]])
print(var)
var.ndim
var.shape


[[1 2 3 9 0]
 [4 5 6 6 9]]


(2, 5)

In [7]:
import numpy as np
var = np.array([1,2,3,4,5])
print(var)
var.ndim
var.shape

[1 2 3 4 5]


(5,)

In [8]:
a.shape,b.shape   # Displays the no.of columns,no.of rows of the array

((3,), (2, 3))

In [9]:
a.dtype,b.dtype    # Data type of array

(dtype('int64'), dtype('float64'))

In [10]:
import numpy as np
c=np.array([[1,2,3,4],[5,6,7,8]])
c[:,2]


array([3, 7])

In [11]:
c[1,1] #acessing a specific elemants

6

In [12]:
c[0,:] #slicing

array([1, 2, 3, 4])

In [13]:
c[:,2]

array([3, 7])

In [14]:
d=np.array([[[1,2],[2,3],[3,4],[5,6]]])
d
#([[[],[],[]]])

array([[[1, 2],
        [2, 3],
        [3, 4],
        [5, 6]]])

In [15]:
d.ndim

3

In [16]:
s=np.zeros((2,7))
s

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [17]:
s=np.ones((2,3))
s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
s=np.full((2,3),100)
s

array([[100, 100, 100],
       [100, 100, 100]])

In [19]:
s=np.random.rand(4,2) #takes random values
s

array([[0.94744445, 0.49640522],
       [0.74647929, 0.87827641],
       [0.74025484, 0.78619566],
       [0.26207391, 0.47016144]])

In [20]:
c=np.eye(3)# create an identity martrics identity or eye
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
import numpy as np
a=np.array([1,2,3,4])
b=a.copy()
b[0]-12
b

array([1, 2, 3, 4])

In [22]:
a=np.array([1,2,3,4]) #any calulation can be done
a=a+2
a

array([3, 4, 5, 6])